/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppCommunicationRouteImport } from './routes/_app.communication'
import { Route as AppAcademicRouteImport } from './routes/_app.academic'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppParentsIndexRouteImport } from './routes/_app.parents.index'
import { Route as AppStudentsListRouteImport } from './routes/_app.students.list'
import { Route as AppSettingsStaffRouteImport } from './routes/_app.settings.staff'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsSchoolProfileRouteImport } from './routes/_app.settings.school-profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsBrandingRouteImport } from './routes/_app.settings.branding'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsAcademicYearRouteImport } from './routes/_app.settings.academic-year'
import { Route as AppReportsDailyAttendanceRouteImport } from './routes/_app.reports.daily-attendance'
import { Route as AppParentsListRouteImport } from './routes/_app.parents.list'
import { Route as AppParentsParentIdRouteImport } from './routes/_app.parents.$parentId'
import { Route as AppStudentsClassIdIndexRouteImport } from './routes/_app.students.$classId.index'
import { Route as AppStudentsClassIdStudentIdRouteImport } from './routes/_app.students.$classId.$studentId'
import { Route as AppAcademicClassesClassIdRouteImport } from './routes/_app.academic.classes.$classId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppParentsIndexRoute = AppParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsListRoute = AppStudentsListRouteImport.update({
  id: '/students/list',
  path: '/students/list',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsStaffRoute = AppSettingsStaffRouteImport.update({
  id: '/settings/staff',
  path: '/settings/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSchoolProfileRoute =
  AppSettingsSchoolProfileRouteImport.update({
    id: '/settings/school-profile',
    path: '/settings/school-profile',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/settings/branding',
  path: '/settings/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAcademicYearRoute = AppSettingsAcademicYearRouteImport.update({
  id: '/settings/academic-year',
  path: '/settings/academic-year',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsDailyAttendanceRoute =
  AppReportsDailyAttendanceRouteImport.update({
    id: '/daily-attendance',
    path: '/daily-attendance',
    getParentRoute: () => AppReportsRoute,
  } as any)
const AppParentsListRoute = AppParentsListRouteImport.update({
  id: '/parents/list',
  path: '/parents/list',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsParentIdRoute = AppParentsParentIdRouteImport.update({
  id: '/parents/$parentId',
  path: '/parents/$parentId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsClassIdIndexRoute = AppStudentsClassIdIndexRouteImport.update({
  id: '/students/$classId/',
  path: '/students/$classId/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsClassIdStudentIdRoute =
  AppStudentsClassIdStudentIdRouteImport.update({
    id: '/students/$classId/$studentId',
    path: '/students/$classId/$studentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAcademicClassesClassIdRoute =
  AppAcademicClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AppAcademicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/academic': typeof AppAcademicRouteWithChildren
  '/communication': typeof AppCommunicationRoute
  '/fees': typeof AppFeesRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/parents/$parentId': typeof AppParentsParentIdRoute
  '/parents/list': typeof AppParentsListRoute
  '/reports/daily-attendance': typeof AppReportsDailyAttendanceRoute
  '/settings/academic-year': typeof AppSettingsAcademicYearRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/school-profile': typeof AppSettingsSchoolProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/staff': typeof AppSettingsStaffRoute
  '/students/list': typeof AppStudentsListRoute
  '/parents/': typeof AppParentsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/academic/classes/$classId': typeof AppAcademicClassesClassIdRoute
  '/students/$classId/$studentId': typeof AppStudentsClassIdStudentIdRoute
  '/students/$classId/': typeof AppStudentsClassIdIndexRoute
}
export interface FileRoutesByTo {
  '/academic': typeof AppAcademicRouteWithChildren
  '/communication': typeof AppCommunicationRoute
  '/fees': typeof AppFeesRoute
  '/': typeof AppIndexRoute
  '/parents/$parentId': typeof AppParentsParentIdRoute
  '/parents/list': typeof AppParentsListRoute
  '/reports/daily-attendance': typeof AppReportsDailyAttendanceRoute
  '/settings/academic-year': typeof AppSettingsAcademicYearRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/branding': typeof AppSettingsBrandingRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/school-profile': typeof AppSettingsSchoolProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/staff': typeof AppSettingsStaffRoute
  '/students/list': typeof AppStudentsListRoute
  '/parents': typeof AppParentsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/academic/classes/$classId': typeof AppAcademicClassesClassIdRoute
  '/students/$classId/$studentId': typeof AppStudentsClassIdStudentIdRoute
  '/students/$classId': typeof AppStudentsClassIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/academic': typeof AppAcademicRouteWithChildren
  '/_app/communication': typeof AppCommunicationRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/parents/$parentId': typeof AppParentsParentIdRoute
  '/_app/parents/list': typeof AppParentsListRoute
  '/_app/reports/daily-attendance': typeof AppReportsDailyAttendanceRoute
  '/_app/settings/academic-year': typeof AppSettingsAcademicYearRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/branding': typeof AppSettingsBrandingRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/school-profile': typeof AppSettingsSchoolProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/staff': typeof AppSettingsStaffRoute
  '/_app/students/list': typeof AppStudentsListRoute
  '/_app/parents/': typeof AppParentsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/academic/classes/$classId': typeof AppAcademicClassesClassIdRoute
  '/_app/students/$classId/$studentId': typeof AppStudentsClassIdStudentIdRoute
  '/_app/students/$classId/': typeof AppStudentsClassIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic'
    | '/communication'
    | '/fees'
    | '/reports'
    | '/parents/$parentId'
    | '/parents/list'
    | '/reports/daily-attendance'
    | '/settings/academic-year'
    | '/settings/billing'
    | '/settings/branding'
    | '/settings/notifications'
    | '/settings/school-profile'
    | '/settings/security'
    | '/settings/staff'
    | '/students/list'
    | '/parents/'
    | '/reports/'
    | '/settings/'
    | '/students/'
    | '/academic/classes/$classId'
    | '/students/$classId/$studentId'
    | '/students/$classId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/academic'
    | '/communication'
    | '/fees'
    | '/'
    | '/parents/$parentId'
    | '/parents/list'
    | '/reports/daily-attendance'
    | '/settings/academic-year'
    | '/settings/billing'
    | '/settings/branding'
    | '/settings/notifications'
    | '/settings/school-profile'
    | '/settings/security'
    | '/settings/staff'
    | '/students/list'
    | '/parents'
    | '/reports'
    | '/settings'
    | '/students'
    | '/academic/classes/$classId'
    | '/students/$classId/$studentId'
    | '/students/$classId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/academic'
    | '/_app/communication'
    | '/_app/fees'
    | '/_app/reports'
    | '/_app/'
    | '/_app/parents/$parentId'
    | '/_app/parents/list'
    | '/_app/reports/daily-attendance'
    | '/_app/settings/academic-year'
    | '/_app/settings/billing'
    | '/_app/settings/branding'
    | '/_app/settings/notifications'
    | '/_app/settings/school-profile'
    | '/_app/settings/security'
    | '/_app/settings/staff'
    | '/_app/students/list'
    | '/_app/parents/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/students/'
    | '/_app/academic/classes/$classId'
    | '/_app/students/$classId/$studentId'
    | '/_app/students/$classId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communication': {
      id: '/_app/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic': {
      id: '/_app/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/parents/': {
      id: '/_app/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof AppParentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/list': {
      id: '/_app/students/list'
      path: '/students/list'
      fullPath: '/students/list'
      preLoaderRoute: typeof AppStudentsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/staff': {
      id: '/_app/settings/staff'
      path: '/settings/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof AppSettingsStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/school-profile': {
      id: '/_app/settings/school-profile'
      path: '/settings/school-profile'
      fullPath: '/settings/school-profile'
      preLoaderRoute: typeof AppSettingsSchoolProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/branding': {
      id: '/_app/settings/branding'
      path: '/settings/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/academic-year': {
      id: '/_app/settings/academic-year'
      path: '/settings/academic-year'
      fullPath: '/settings/academic-year'
      preLoaderRoute: typeof AppSettingsAcademicYearRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/daily-attendance': {
      id: '/_app/reports/daily-attendance'
      path: '/daily-attendance'
      fullPath: '/reports/daily-attendance'
      preLoaderRoute: typeof AppReportsDailyAttendanceRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/parents/list': {
      id: '/_app/parents/list'
      path: '/parents/list'
      fullPath: '/parents/list'
      preLoaderRoute: typeof AppParentsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents/$parentId': {
      id: '/_app/parents/$parentId'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId'
      preLoaderRoute: typeof AppParentsParentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$classId/': {
      id: '/_app/students/$classId/'
      path: '/students/$classId'
      fullPath: '/students/$classId/'
      preLoaderRoute: typeof AppStudentsClassIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$classId/$studentId': {
      id: '/_app/students/$classId/$studentId'
      path: '/students/$classId/$studentId'
      fullPath: '/students/$classId/$studentId'
      preLoaderRoute: typeof AppStudentsClassIdStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/classes/$classId': {
      id: '/_app/academic/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/academic/classes/$classId'
      preLoaderRoute: typeof AppAcademicClassesClassIdRouteImport
      parentRoute: typeof AppAcademicRoute
    }
  }
}

interface AppAcademicRouteChildren {
  AppAcademicClassesClassIdRoute: typeof AppAcademicClassesClassIdRoute
}

const AppAcademicRouteChildren: AppAcademicRouteChildren = {
  AppAcademicClassesClassIdRoute: AppAcademicClassesClassIdRoute,
}

const AppAcademicRouteWithChildren = AppAcademicRoute._addFileChildren(
  AppAcademicRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsDailyAttendanceRoute: typeof AppReportsDailyAttendanceRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsDailyAttendanceRoute: AppReportsDailyAttendanceRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRouteWithChildren
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppFeesRoute: typeof AppFeesRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppParentsParentIdRoute: typeof AppParentsParentIdRoute
  AppParentsListRoute: typeof AppParentsListRoute
  AppSettingsAcademicYearRoute: typeof AppSettingsAcademicYearRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSchoolProfileRoute: typeof AppSettingsSchoolProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsStaffRoute: typeof AppSettingsStaffRoute
  AppStudentsListRoute: typeof AppStudentsListRoute
  AppParentsIndexRoute: typeof AppParentsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppStudentsClassIdStudentIdRoute: typeof AppStudentsClassIdStudentIdRoute
  AppStudentsClassIdIndexRoute: typeof AppStudentsClassIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRouteWithChildren,
  AppCommunicationRoute: AppCommunicationRoute,
  AppFeesRoute: AppFeesRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppParentsParentIdRoute: AppParentsParentIdRoute,
  AppParentsListRoute: AppParentsListRoute,
  AppSettingsAcademicYearRoute: AppSettingsAcademicYearRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSchoolProfileRoute: AppSettingsSchoolProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsStaffRoute: AppSettingsStaffRoute,
  AppStudentsListRoute: AppStudentsListRoute,
  AppParentsIndexRoute: AppParentsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppStudentsClassIdStudentIdRoute: AppStudentsClassIdStudentIdRoute,
  AppStudentsClassIdIndexRoute: AppStudentsClassIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
